### ISSUE TITLE
How to handle data between different user states?

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treemapper#291]
What is the desired behavior to handle data between the following states:

1. not logged in user
2. first logged in user
3. logged out user after once having been logged in
4. different logged in user

What are our rules to handle the existing local and server data if the app switches between these four states? Affected data are 
- user profile, e.g. country influencing the metric to show registered trees (cm vs inches)
- registered trees
- customized species list
- ...

Examples:

1. Some trees are registered and some species are locally modified with pictures, descriptions and aliases without having been logged in and the the user registers and logs into the app. 
Possibly behavior: All local data uploaded will be associated with this user account on the server. All existing server data from this user will be displayed (a feature to come later for the app). 

2. The user logs out and logs into another user account. 
Possibly behavior: All local data is not yet linked to any user account and will only be associated with the account it will be uploaded to. Any server data of the former user account will be removed locally and the data from the newly logged in user account will be shown.

3. User logs out and no new user logs in:
Possible behavior: (1) All user data already uploaded to the user account will be cleaned locally and not shown any more or (2) all user data from the last logged in user account is shown and replaced when the same or another user logging in again.

Open questions:

- Should already uploaded registrations be downloaded into the local database or only displayed directly from the server without local caching?
- New registration are uploaded manually on users request and deleted locally also manually. Will this be changed or kept?
- How can this be done best for the customized species list? Are uploaded changes marked the same way as for registrations? Is changing the species list possible if no user is logged in?

**Comment by sagararyal** [comment]
@norbertschuler 

Any data that have started to sync with user A, will be synced to the server for user A.

We discussed about sharing backend generated tokens for uploading remaining items, instead of using access tokens.

Next, if this user logs out and another logs in,

Auto upload should be disabled.

Any remaining items would then be uploaded from user B account should the user start the upload process.

-- We could offer `clean local` button, that clears everything locally.
-- country would only determine on how the data from database displayed, it does not play a role in the actual data, we store in m, and cm by default.

Important note: Tree Mapper will not delete local data just because a user logged out.
This could happen due to many reasons, including intentional log out; access token expired, app update, etc.

**Comment by norbertschuler** [comment]
Ok, customized species data gets cleaned now if a user is logged out while tree registrations are kept and can be uploaded to a different account.
